### ISSUE TITLE
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

### ISSUE THREAD

**Issue by kkkkyp** [George730/E-ResGAT#6]
Traceback (most recent call last):
  File "D:/PyCharm/Py_project/E-ResGAT-master/fit_model.py", line 189, in <module>
  File "D:/PyCharm/Py_project/E-ResGAT-master/fit_model.py", line 114, in fit
    acc_val, loss_val, val_output = predict_(alg, model, label, loss_fn, val)
  File "D:/PyCharm/Py_project/E-ResGAT-master/fit_model.py", line 145, in predict_
    batch_loss = loss_fn(batch_output, label[batch_edges])
  File "D:\Anaconda\envs\GraphSAGE\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda\envs\GraphSAGE\lib\site-packages\torch\nn\modules\loss.py", line 948, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "D:\Anaconda\envs\GraphSAGE\lib\site-packages\torch\nn\functional.py", line 2422, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "D:\Anaconda\envs\GraphSAGE\lib\site-packages\torch\nn\functional.py", line 1591, in log_softmax
    ret = input.log_softmax(dim)
**IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)**

Hello, can you help me solve this problem?

**Comment by George730** [comment]
you can add one more dimension to 'input', try input = torch.unsqueeze(input, 0).

**Comment by kkkkyp** [comment]
I try chage batch_loss = loss_fn(batch_output, label[batch_edges]) to  
           if len(batch_output.shape) == 1:
                batch_output = torch.unsqueeze(batch_output,0)
            batch_loss = loss_fn(torch.tensor(batch_output, dtype=torch.float32),
                                 torch.FloatTensor(torch.tensor(label[np.array(batch_edges)], dtype=torch.float32))) 
**then, This error has occurred。**
D:/PyCharm/Py_project/E-ResGAT-master/fit_model.py:148: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  batch_loss = loss_fn(torch.tensor(batch_output, dtype=torch.float32),
D:/PyCharm/Py_project/E-ResGAT-master/fit_model.py:149: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.FloatTensor(torch.tensor(label[np.array(batch_edges)], dtype=torch.float32)))
Traceback (most recent call last):
  File "D:/PyCharm/Py_project/E-ResGAT-master/fit_model.py", line 189, in <module>
    fit(args)
  File "D:/PyCharm/Py_project/E-ResGAT-master/fit_model.py", line 114, in fit
    acc_val, loss_val, val_output = predict_(alg, model, label, loss_fn, val)  File "D:/PyCharm/Py_project/E-ResGAT-master/fit_model.py", line 149, in predict_
    torch.FloatTensor(torch.tensor(label[np.array(batch_edges)], dtype=torch.float32)))
  File "D:\Anaconda\envs\gsage\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda\envs\gsage\lib\site-packages\torch\nn\modules\loss.py", line 948, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "D:\Anaconda\envs\gsage\lib\site-packages\torch\nn\functional.py", line 2422, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "D:\Anaconda\envs\gsage\lib\site-packages\torch\nn\functional.py", line 2216, in nll_loss
    .format(input.size(0), target.size(0)))
ValueError: Expected input batch_size (1) to match target batch_size (500).
